### ISSUE TITLE
A list of (small) issues/typos with the survivor Talkers

### ISSUE THREAD

**Issue by MisterMayoNL** [Tsuey/L4D2-Community-Update#415]
### Description

Multiple small errors in the talker files that are easily fixed.
Sorry if some of these are already reported, but I'm sure that most of these have not been reported yet.

**1.** Rochelle PlayerFriendlyFire2Producer lines don't play. (Fixed by changing IsFriendlyFire to Is**Not**FriendlyFire)

**2.** Louis L4D1TeamKillManager has wrong requirement. (Fixed by changing IsNotSaidFaultFriendlyFire**NamVet** to IsNotSaidFaultFriendlyFire**Manager**)

**3.** Crash Course Intro has missing responses.
- Zoey misses IntroCrashR21TeenGirl (voiceline DLC2Misc01 is to be used)
- Zoey misses IntroCrashR39TeenGirl (reaction from IntroCrashR37Manager. Voiceline Generic15 is to be used)
- Louis L4D1PlayerCrashCourseIntroManager second voiceline should continue with TeenGirl IntroCrash21 instead of IntroCrash04
- ~~Francis IntroCrashR08Biker is missing IntroEnd~~

**4.** Coach NickC1AttitudeCoach refrences the wrong/a non-existing voiceline. (Fixed by changing YouAreWelcome09 to Thanks09)

**5.** Ellis DLC1_C6M2_SafeRoomConvo19gMechanic has a typo that breaks the voiceline. (Fixed by changing DLC1_C6M2_SafeRoomConv21 to DLC1_C6M2_SafeRoomConv**o**21)

**6.** The L4D1 crew still shouts to close the saferoom door even when alone. (Fixed by adding IsNotAlone requirement to L4D1PlayerLockTheDoorCheckPoint)

**7.** Ellis does not have a PlayerReviveFriendFF Rule & Response despite the other L4D2 Survivors having them. Even Rochelle has one despite using WitchChasing voicelines for it. I can only conclude that it was forgotten with TLS.

**8.** Wrong ItemDonor instances.
- Louis ItemDonorBikerManager has wrong YouAreWelcome target. (Fixed by changing coach instances to biker)
- ~~Ellis ItemDonorBikerMechanic has wrong YouAreWelcome target. (Fixed by changing gambler instances to biker)~~
- Rochelle ItemDonor does not contain one for Gambler/Nick. (Might not be an issue and uses PlayerGivenItemProducer instead?)

**9.** Wrong predelay timings.
- Nick ItemDonor lines mostly use wrong predelay time of .2,.5 instead of 2,2.5
- Rochelle ReviveThanksCoachProducer first voiceline has wrong predelay time of 2,2.5 instead of .2,.5
- Ellis ReviveThanksCoachMechanic & ReviveThanksGamblerMechanic first two voicelines have wrong predelay time of 2,2.5 instead of .2,.5
- Survivor Teamkill voiceline predelay timings are inconsistent. Bill, Francis, Coach & Zoey use predelay .5,1.25 while Louis, Nick, Ellis & Rochelle use predelay 1,1.75

**10.** Nick YouAreWelcomeMechanicGambler uses the wrong Concept. (Fixed by changing ConceptPlayerYouAreWelcome to ConceptYouAreWelcome)

**11.** The C1M2 Survival map has no working Tank friendlyfire lines. Caused by both PlayerFriendlyFireTank as well as PlayerFriendlyFireTankC1 responses not passing requirements.

**12.** Francis & Zoey L4D1BotNoteHumanAttention uses the wrong requirement. (Fixed by changing IsInSafeSpot to IsInStartArea)

**Comment by alexiscoutinho** [comment]
Partial/minor duplicate of #405.

@MisterMayoNL Also, are all these problems still present in the updated talker files of this repo?

**Comment by MisterMayoNL** [comment]
@alexiscoutinho Double checked, and the only issues that's already fixed is the second point in 8. All the other issues are still present.

**Comment by xanaguy** [comment]
> @alexiscoutinho Double checked, and the only issues that are already fixed are the last point in 3 and the second point in 8. All the other issues are still present. I've edited the issue to reflect that.

All issues have been fixed, granted, not all are in the way you've suggested due to them being either impossible or not optimal. Other changes have been included, so I'm uploading all of it now.

**Comment by MisterMayoNL** [comment]
@xanaguy nice to see it fixed so quickly! I did notice however that PlayerFriendlyFireTankCoachProducer & PlayerFriendlyFireTankGamblerProducer still have the isNotmap_c1m2_streets requirement. I'm guessing that's not supposed to be there.

**Comment by xanaguy** [comment]
They are meant to be. It's because the lines in those rules still call out the tank by name. There's also the "C1M1orC1M2" criteria in the PlayerFriendlyFireTankC1M2Producer rule, while the name may not be the most accurate, the main thing is that this particular rule will work on c1m1_hotel or c1m2_streets, it will pass if the map is either of the two. The "isNotmap" criteria is all set as separate critera in the remaining rules to ensure that those lines do not fire on the two maps.

**Comment by MisterMayoNL** [comment]
Yes that's true, but doesn't this still result in those lines not playing in the C1M2 survival map?

I noticed it because the other L4D2 survivors had the isNotmap_c1m2_streets requirement removed.

**Comment by xanaguy** [comment]
Right, because when a map criteria is set for a rule, specifically, to be on this map (not to be confused with a "not" clause), they usually would have an assigned weight value, usually 100, to override general cases. It looks like I did forget to remove that other criteria for the other rules, so I'll fix and upload it know. If you want, please test and make sure that the tank isn't called out by name in the c1m2 in coop. It shouldn't, but it's best to be sure.

**Comment by MisterMayoNL** [comment]
Well I've tested the current version and it works as it should. Didn't hear any survivor say Tank once in c1m2 coop. In c1m2 survival it works as normal.

One last thing I want to mention is that all the FriendlyFireTank rules have IsNotIncapacitated twice, and the _auto_NotSpottedVehicle requirement is not in the FriendlyFireTankC1 rules (gotta be honest, I don't know what it does, but I'm gonna mention it just in case).

**Comment by xanaguy** [comment]
It's a matter of whether all criteria of a rule is complete, and even then, which rule has the greater weight. This setup should allow the tankfriendlyfire lines to play on c1m2 survival, but have a different set used if the mode were versus or coop.
